# Elenco porte da monitorare per /usr/local/bin/apply-monitor-rules.sh e /usr/local/bin/check-traffic.sh
#22   # ssh
80   # http
445  # samba
7125 # klipper
9000 # portainer
9090 # cockpit
9981 # tvheadend http !wol-only
9982 # tvheadend https !wol-only
